"""add is_admin group

Revision ID: 75382d96ec11
Revises: 9c0e1adcec79
Create Date: 2025-06-03 19:45:51.961414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75382d96ec11'
down_revision: Union[str, None] = '9c0e1adcec79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('is_admin', sa.Boolean(), server_default='FALSE', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 'is_admin')
    # ### end Alembic commands ###
