"""auto-add staff reset to Staff model

Revision ID: ec03aa03da29
Revises: 75382d96ec11
Create Date: 2025-06-05 11:06:56.652878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec03aa03da29'
down_revision: Union[str, None] = '75382d96ec11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('staff_reset', sa.Boolean(), server_default='TRUE', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 'staff_reset')
    # ### end Alembic commands ###
